### PR TITLE
Fixing bug in Observe structure

### PR DESCRIPTION
**Pull request by dotstormz**
observe is looking for 'attributes' instead of 'attribute'. This fixes a JavaScript error that appears in Safari.

### CODE REVIEW

**Comment by dotstormz** [comment]
@Jabher Hi mate sorry it took so long. Please let me know if this is the only change that needs to be executed.

**Comment by Jabher** [comment]
This project have not seen a commits for a long time, it can wait :D One more thing - can you please apply same change for a "dist" folder? there's a built files there

**Comment by dotstormz** [comment]
@Jabher Do you mean "build" folder?

**Comment by Jabher** [comment]
Yeah, exactly. As I said - it was a looong time since I've been doing something here 😅

**Comment by Jabher** [comment]
Wow. Nice changes :) Thanks a lot!

**Pull request merged**
