### PR TITLE
Fixing bug #10.

### PR DESCRIPTION
**Pull request by roura356a**
Bug explained in #10.

### CODE REVIEW

**Comment by Jabher** [comment]
So, it can be fixed in simpler (and shorter) way - by replacing `var topParent = element.parentElement;` with `var topParent = element;` and then `while` loop will exit asap there is no `parentElement` for `topParent`, then, as long as `topParent !== document.documentElement` - it will perform the return.

Can you edit your PR please?

**Comment by roura356a** [comment]
Oh, sorry I didn't read your answer. I will update it!

**Comment by roura356a** [comment]
Hi Jabher, sorry for the delay. I updated the PR following your suggestion. It works!

**Comment by Jabher** [comment]
Thank you a lot! 🍻

**Pull request merged**
